### ISSUE TITLE
Time freezes on iOS

### ISSUE THREAD

**Issue by SalavatR** [AGulev/defold-extension-uptime#2]
Hi!
Have problem on iOS build, when i hide application time freezes and when activate app time has same value, app reopening helps sometimes

Here is the same problem described:
https://www.generacodice.com/en/articolo/1789391/frozen-uptime-on-ios-iphone

**Comment by AGulev** [comment]
Hm. 
According to the doc https://developer.apple.com/documentation/foundation/nsprocessinfo/1414553-systemuptime

>The amount of time **the system has been awake** since the last time it was restarted.

So, do you mean time freezes when you lock device or when app is in background?

**Comment by SalavatR** [comment]
> Hm.
> According to the doc https://developer.apple.com/documentation/foundation/nsprocessinfo/1414553-systemuptime
> 
> > The amount of time **the system has been awake** since the last time it was restarted.
> 
> So, do you mean time freezes when you lock device or when app is in background?

when app is in background
on Android it works perfect

**Comment by AGulev** [comment]
I'll take a look today later

**Comment by AGulev** [comment]
@SalavatR I made some improvements in example for the extension and can't reproduce your bug 
![telegram-cloud-photo-size-2-5366092450285860452-y](https://user-images.githubusercontent.com/2209596/134779041-a6283cf1-6674-4c57-94cd-074fb3877252.jpg)

**Comment by AGulev** [comment]
https://developer.apple.com/forums/thread/98682

**Comment by AGulev** [comment]
I released a new version where the issue fixed https://github.com/AGulev/defold-extension-uptime/releases/tag/1.2.0
